"""Report and evaluation data models, plus scoring-related schemas.

These Pydantic models define the structured output that the backend consumes,
and the structured output the evaluator LLM must return for each answer.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal, Optional

from pydantic import BaseModel, Field

from app.knowledge.university_service import UniversityMatch

RecommendationBand = Literal["Strong", "Likely", "Borderline", "Weak"]
TurnKind = Literal["greeting", "question", "probe", "closing"]

DISCLAIMER = (
    "This report is generated by an automated mock-interview tool for "
    "preparation purposes only. It is NOT an official visa adjudication and "
    "does not predict or represent any government decision."
)


class ExtractedEntity(BaseModel):
    """A single structured fact pulled from an answer.

    Modeled as an explicit key/value pair (not a free-form dict) so the schema
    is valid for OpenAI strict structured outputs and every other provider.
    """

    key: str = Field(description="Field name, e.g. 'university' or 'sponsor'.")
    value: str = Field(description="The extracted value.")


class AnswerEvaluation(BaseModel):
    """Structured analysis of a single applicant answer (LLM output)."""

    extracted_entities: list[ExtractedEntity] = Field(
        default_factory=list,
        description="Structured facts pulled from the answer (e.g. university).",
    )
    matched_signals: list[str] = Field(
        default_factory=list,
        description="Expected positive signals the answer satisfied.",
    )
    detected_red_flags: list[str] = Field(
        default_factory=list,
        description="Red-flag patterns observed in the answer.",
    )
    inconsistencies: list[str] = Field(
        default_factory=list,
        description="Contradictions vs. earlier answers or the provided profile.",
    )
    vagueness: float = Field(
        default=0.0, ge=0.0, le=1.0, description="0 = specific, 1 = very vague."
    )
    coached_likelihood: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Likelihood the answer was memorized / rote-coached.",
    )
    answer_quality: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Overall credibility/quality of the answer.",
    )
    needs_probe: bool = Field(
        default=False, description="Whether a follow-up question is warranted."
    )
    probe_reason: str = Field(
        default="", description="What specifically should be probed, if anything."
    )
    rationale: str = Field(default="", description="Short justification.")
    # Populated by code (not the LLM): the topic this evaluation belongs to.
    topic_id: Optional[str] = None


class ReportNarrative(BaseModel):
    """Human-readable narrative synthesized by the LLM for the final report."""

    summary: str
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)


class TopicResult(BaseModel):
    """Per-topic scored outcome included in the report."""

    topic_id: str
    label: str
    score: float = Field(ge=0.0, le=1.0)
    weight: float
    red_flags: list[str] = Field(default_factory=list)
    inconsistencies: list[str] = Field(default_factory=list)
    probes_used: int = 0
    summary: str = ""


class TranscriptEntry(BaseModel):
    """A single line in the interview transcript."""

    role: Literal["officer", "applicant"]
    content: str
    turn_kind: Optional[TurnKind] = None
    topic_id: Optional[str] = None
    topic_label: Optional[str] = None
    is_probe: bool = False


class InterviewReport(BaseModel):
    """The full, detailed report delivered to the backend."""

    session_id: str
    generated_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    country: str
    visa_type: str
    display_name: str

    overall_score: float = Field(ge=0.0, le=100.0)
    recommendation_band: RecommendationBand
    recommendation: str

    summary: str = ""
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)

    topic_results: list[TopicResult] = Field(default_factory=list)
    red_flags: list[str] = Field(default_factory=list)
    consistency_findings: list[str] = Field(default_factory=list)
    coaching_signal: float = Field(default=0.0, ge=0.0, le=1.0)

    university_assessment: Optional[UniversityMatch] = None

    probing_summary: str = ""
    transcript: list[TranscriptEntry] = Field(default_factory=list)
    model_info: dict = Field(default_factory=dict)
    disclaimer: str = DISCLAIMER
